---
- name: Stop service on all nodes
  become: true
  ansible.builtin.systemd:
    name: "{{ core_update_service_name }}"
    state: stopped

- name: Get currently installed package version
  become: true
  ansible.builtin.shell: >
    ls {{ core_update_base_dir }}/Packages | grep "{{ core_update_package }}-" | awk -F'-' '{print $2}'
  register: installed_version
  changed_when: false
  ignore_errors: true
  when: inventory_hostname == groups['core_cluster'][0]

- name: Debug installed version
  ansible.builtin.debug:
    var: installed_version.stdout
  when: inventory_hostname == groups['core_cluster'][0]

- name: Update package if versions differ
  become: true
  ansible.builtin.command:
    cmd: "{{ core_update_base_dir }}/Launcher.dll pkg -s http://main.eacs.transset.ru update {{ core_update_package }} {{ version }}"
    creates: "{{ core_update_base_dir }}/Packages/{{ core_update_package }}-{{ version }}"
  when:
    - inventory_hostname == groups['core_cluster'][0]
    - installed_version.stdout != version

- name: Remove Packages directory on non-first nodes
  become: true
  ansible.builtin.file:
    path: "{{ core_update_base_dir }}/Packages"
    state: absent
  when: inventory_hostname != groups['core_cluster'][0]

- name: Copy Packages directory from first node to others
  become: true
  ansible.builtin.copy:
    src: "{{ core_update_base_dir }}/Packages/"
    dest: "{{ core_update_base_dir }}/Packages"
    remote_src: true
    mode: preserve
  delegate_to: "{{ groups['core_cluster'][0] }}"
  when: inventory_hostname != groups['core_cluster'][0]

- name: Verify rsync is installed
  become: true
  ansible.builtin.package:
    name: rsync
    state: present

- name: Restart service on all nodes
  become: true
  ansible.builtin.systemd:
    name: "{{ core_update_service_name }}"
    state: restarted
